# Generated by Django 4.0.1 on 2022-08-22 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monsters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('zone_mob', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zones.zones')),
            ],
        ),
    ]
