# Generated by Django 4.0.1 on 2022-09-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsters',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='monsters',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='name'),
        ),
    ]
