# Generated by Django 4.0.1 on 2023-01-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_alter_zones_img_alter_zones_name_and_more'),
        ('items', '0008_alter_item_options_alter_item_table'),
        ('monsters', '0002_alter_monsters_level_alter_monsters_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monsters',
            new_name='Monster',
        ),
        migrations.AlterModelOptions(
            name='monster',
            options={'verbose_name': 'monster', 'verbose_name_plural': 'monsters'},
        ),
        migrations.AlterModelTable(
            name='monster',
            table='rise_monster',
        ),
    ]
