# Generated by Django 4.0.1 on 2023-03-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_title', models.CharField(max_length=64, verbose_name='msg_title')),
                ('msg_type', models.CharField(choices=[('Items', 'Items'), ('Monsters', 'Monsters'), ('Drops', 'Drops'), ('Rewards', 'Rewards'), ('Quests', 'Quests'), ('News', 'News'), ('Other', 'Other')], default=('Items', 'Items'), max_length=16, verbose_name='msg_type')),
                ('msg_description', models.CharField(max_length=500, verbose_name='msg_description')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'rise_contact',
            },
        ),
    ]
