# Generated by Django 4.0.1 on 2023-03-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='msg_read',
            field=models.BooleanField(default=False, verbose_name='msg_read'),
        ),
    ]
