# Generated by Django 4.0.1 on 2022-08-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('required_level', models.PositiveSmallIntegerField(default=1)),
                ('img', models.ImageField(blank=True, null=True, upload_to='zones/')),
            ],
        ),
    ]
