# Generated by Django 4.0.1 on 2022-09-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zones',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='zones/', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='zones',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='zones',
            name='required_level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='required_level'),
        ),
    ]
