# Generated by Django 4.0.1 on 2023-01-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_rename_monsters_monster_alter_monster_options_and_more'),
        ('quests', '0006_rename_quests_quest_alter_quest_options_and_more'),
        ('zones', '0002_alter_zones_img_alter_zones_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zones',
            new_name='Zone',
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'zone', 'verbose_name_plural': 'zones'},
        ),
        migrations.AlterModelTable(
            name='zone',
            table='rise_zone',
        ),
    ]
