# Generated by Django 4.0.1 on 2022-09-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftsidemenu',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='leftsidemenu',
            name='priority',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='priority'),
        ),
    ]
