# Generated by Django 4.0.1 on 2022-09-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.TextField(verbose_name='article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateField(auto_now=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=64, verbose_name='title'),
        ),
    ]
