# Generated by Django 4.0.1 on 2023-01-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_article_alter_article_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='rise_article',
        ),
    ]
