# Generated by Django 4.0.1 on 2023-03-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_alter_article_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='full_article',
            field=models.TextField(default='', verbose_name='full_article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.CharField(max_length=256, verbose_name='article'),
        ),
    ]
