# Generated by Django 4.0.1 on 2023-03-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_full_article_alter_article_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.TextField(max_length=256, verbose_name='article'),
        ),
    ]
