# Generated by Django 4.0.1 on 2022-08-22 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('dropped_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='monsters.monsters')),
            ],
        ),
    ]
