# Generated by Django 4.0.1 on 2022-09-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='name'),
        ),
    ]
