# Generated by Django 4.0.1 on 2022-10-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_items_img_alter_items_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_type',
            field=models.CharField(choices=[('Sword', 'Sword'), ('Dagger', 'Dagger'), ('Bow', 'Bow'), ('Axe', 'Axe'), ('Spear', 'Spear'), ('Staff', 'Staff'), ('Mace', 'Mace')], default='', max_length=32, verbose_name='item_type'),
        ),
    ]
