# Generated by Django 4.0.1 on 2022-10-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_items_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_type',
            field=models.CharField(choices=[('Sword', 'Sword'), ('Dagger', 'Dagger'), ('Bow', 'Bow'), ('Axe', 'Axe'), ('Spear', 'Spear'), ('Staff', 'Staff'), ('Mace', 'Mace'), ('Warrior Armor', 'Warrior Armor'), ('Mage Armor', 'Mage Armor'), ('Rogue Armor', 'Rogue Armor'), ('Priest Armor', 'Priest Armor'), ('Accesories', 'Accesories')], default='', max_length=32, verbose_name='item_type'),
        ),
    ]
