# Generated by Django 4.0.1 on 2023-01-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0002_alter_monsters_level_alter_monsters_name'),
        ('items', '0006_alter_items_item_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
