# Generated by Django 4.0.1 on 2023-01-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_rename_items_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelTable(
            name='item',
            table='rise_item',
        ),
    ]
