# Generated by Django 4.0.1 on 2022-12-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quests', '0004_remove_quests_exp_remove_quests_start_zone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('quest_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quests.quests')),
            ],
        ),
    ]
