# Generated by Django 4.0.1 on 2022-12-07 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_remove_quests_exp_remove_quests_start_zone_and_more'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewards',
            name='quest_id',
        ),
        migrations.AddField(
            model_name='rewards',
            name='quests',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quests.quests'),
        ),
    ]
