# Generated by Django 4.0.1 on 2022-12-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_remove_rewards_quest_id_rewards_quests'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='count'),
        ),
        migrations.AddField(
            model_name='rewards',
            name='reward_type',
            field=models.CharField(choices=[('exp', 'exp'), ('weapon', 'weapon'), ('armor', 'armor'), ('potion', 'potion'), ('bpoint', 'bpoint'), ('scroll', 'scroll'), ('other', 'other')], default='', max_length=16, verbose_name='reward_type'),
        ),
        migrations.AddField(
            model_name='rewards',
            name='upgrade_level',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='upgrade_level'),
        ),
    ]
