# Generated by Django 4.0.1 on 2022-12-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_rewards_count_rewards_reward_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='reward_type',
            field=models.CharField(choices=[('exp', 'exp'), ('weapon', 'weapon'), ('armor', 'armor'), ('potion', 'potion'), ('bpoint', 'bpoint'), ('scroll', 'scroll'), ('coin', 'coin'), ('other', 'other')], default='', max_length=16, verbose_name='reward_type'),
        ),
    ]
