# Generated by Django 4.0.1 on 2023-01-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0006_rename_quests_quest_alter_quest_options_and_more'),
        ('rewards', '0004_alter_rewards_reward_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewards',
            new_name='Reward',
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'verbose_name': 'reward', 'verbose_name_plural': 'rewards'},
        ),
        migrations.AlterModelTable(
            name='reward',
            table='rise_reward',
        ),
    ]
