# Generated by Django 4.0.1 on 2022-08-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quests',
            name='description',
        ),
        migrations.AddField(
            model_name='quests',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
