# Generated by Django 4.0.1 on 2022-09-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_remove_quests_description_quests_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quests',
            name='exp',
            field=models.IntegerField(default=0, verbose_name='exp'),
        ),
        migrations.AlterField(
            model_name='quests',
            name='required_level',
            field=models.PositiveIntegerField(default=1, verbose_name='required_level'),
        ),
        migrations.AlterField(
            model_name='quests',
            name='start_zone',
            field=models.CharField(max_length=64, verbose_name='start_zone'),
        ),
        migrations.AlterField(
            model_name='quests',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
    ]
