# Generated by Django 4.0.1 on 2022-11-30 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_alter_zones_img_alter_zones_name_and_more'),
        ('quests', '0003_alter_quests_exp_alter_quests_required_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quests',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='quests',
            name='start_zone',
        ),
        migrations.RemoveField(
            model_name='quests',
            name='title',
        ),
        migrations.AddField(
            model_name='quests',
            name='description',
            field=models.CharField(default='', max_length=128, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='quests',
            name='npc_name',
            field=models.CharField(default='', max_length=64, verbose_name='npc_name'),
        ),
        migrations.AddField(
            model_name='quests',
            name='quest_name',
            field=models.CharField(default='', max_length=128, verbose_name='quest_name'),
        ),
        migrations.AddField(
            model_name='quests',
            name='quest_zone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zones.zones'),
        ),
        migrations.AddField(
            model_name='quests',
            name='reward',
            field=models.CharField(default='', max_length=256, verbose_name='reward'),
        ),
    ]
