# Generated by Django 4.0.1 on 2022-12-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_remove_quests_exp_remove_quests_start_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quests',
            name='reward',
        ),
    ]
