# Generated by Django 4.0.1 on 2023-01-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_alter_zones_img_alter_zones_name_and_more'),
        ('rewards', '0004_alter_rewards_reward_type'),
        ('quests', '0005_remove_quests_reward'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quests',
            new_name='Quest',
        ),
        migrations.AlterModelOptions(
            name='quest',
            options={'verbose_name': 'quest', 'verbose_name_plural': 'quests'},
        ),
        migrations.AlterModelTable(
            name='quest',
            table='rise_quest',
        ),
    ]
