# Generated by Django 4.0.1 on 2022-08-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('skill_class', models.CharField(blank=True, choices=[('Warrior', 'Warrior'), ('Rogue', 'Rogue'), ('Mage', 'Mage'), ('Priest', 'Priest')], max_length=16, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('skill_tree', models.CharField(choices=[('Train', 'Trainee'), ('Asass', 'Assasin'), ('Arch', 'Archer'), ('Def', 'Defense'), ('Mstr', 'Master'), ('Buff', 'Buff'), ('Heal', 'Heal'), ('Dbf', 'Debuff'), ('Fire', 'Fire'), ('Ice', 'Ice'), ('Light', 'Lighting'), ('Attk', 'Attack')], default='', max_length=32)),
                ('mana', models.SmallIntegerField(default=0)),
                ('cooldown', models.FloatField(default=0)),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/skills/')),
                ('skill_point', models.SmallIntegerField(default=0)),
                ('skill_level', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
