# Generated by Django 4.0.1 on 2022-09-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='cooldown',
            field=models.FloatField(default=0, verbose_name='cooldown'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/skills/', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='mana',
            field=models.SmallIntegerField(default=0, verbose_name='mana'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_class',
            field=models.CharField(blank=True, choices=[('Warrior', 'Warrior'), ('Rogue', 'Rogue'), ('Mage', 'Mage'), ('Priest', 'Priest')], max_length=16, null=True, verbose_name='skill_class'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_level',
            field=models.SmallIntegerField(default=0, verbose_name='skill_level'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_point',
            field=models.SmallIntegerField(default=0, verbose_name='skill_point'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_tree',
            field=models.CharField(choices=[('Train', 'Trainee'), ('Asass', 'Assasin'), ('Arch', 'Archer'), ('Def', 'Defense'), ('Mstr', 'Master'), ('Buff', 'Buff'), ('Heal', 'Heal'), ('Dbf', 'Debuff'), ('Fire', 'Fire'), ('Ice', 'Ice'), ('Light', 'Lighting'), ('Attk', 'Attack')], default='', max_length=32, verbose_name='skill_tree'),
        ),
    ]
