# Generated by Django 4.0.1 on 2023-01-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skills_cooldown_alter_skills_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'skill', 'verbose_name_plural': 'skills'},
        ),
        migrations.AlterModelTable(
            name='skill',
            table='rise_skill',
        ),
    ]
